# Generated by Django 2.0.4 on 2018-05-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_add_base_client_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientconnection',
            old_name='accounts',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='clientconnection',
            old_name='contacts',
            new_name='contact',
        ),
    ]
