# Generated by Django 2.0.4 on 2018-05-15 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_change_field_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CredentialType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendly_name', models.CharField(max_length=80)),
                ('credentials', models.ManyToManyField(to='credentials.Credential')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=190)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to='clients.ClientAccount')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCredentialConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.Credential')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.Project')),
            ],
        ),
        migrations.AddField(
            model_name='credential',
            name='credential_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credentials.CredentialType'),
        ),
        migrations.AddField(
            model_name='credential',
            name='projects',
            field=models.ManyToManyField(through='credentials.ProjectCredentialConnection', to='credentials.Project'),
        ),
    ]
