# Generated by Django 2.0.4 on 2018-05-15 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_add_credentials_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credentialtype',
            name='credentials',
        ),
    ]
