# Generated by Django 2.0.4 on 2018-05-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_remove_many_to_many'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='credential_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='credential',
            name='credential_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
